//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeCV.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjeCVHomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjeCVHomeTexts() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjeCV.Resources.ProjeCVHomeTexts", typeof(ProjeCVHomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Deneyimlerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deneyimlerim {
            get {
                return ResourceManager.GetString("deneyimlerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eğitim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string egitim {
            get {
                return ResourceManager.GetString("egitim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkımda benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hakkimda {
            get {
                return ResourceManager.GetString("hakkimda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hobilerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hobilerim {
            get {
                return ResourceManager.GetString("hobilerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konferanslarım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string konferanslarim {
            get {
                return ResourceManager.GetString("konferanslarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeteneklerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yeteneklerim {
            get {
                return ResourceManager.GetString("yeteneklerim", resourceCulture);
            }
        }
    }
}
